name: GitHub Breakout

on:
  # on.schedule 讓這個 Action 每天 UTC 時間的午夜自動執行一次
  schedule:
    - cron: '0 0 * * *'
  # on.workflow_dispatch 讓我們可以手動觸發這個 Action
  workflow_dispatch:

jobs:
  generate-svgs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 把你的 repo 程式碼載下來
      - uses: actions/checkout@v3

      # Step 2: 執行產生 SVG 的主要 Action
      - uses: cyprieng/github-breakout@v1.0.0
        with:
          github_username: 'yijiunchin'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 注意：這裡會自動抓這個 repo 擁有者的貢獻圖
          # 如果你的 repo 名稱跟帳號不同，才需要手動指定 username

      # Step 3: 自動把新產生的 SVG 檔案 commit 回你的 repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update github-breakout svgs'
          file_pattern: '*.svg'
