name: GitHub Breakout

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-svgs:
    runs-on: ubuntu-latest
    
    # <--- 加上這個 permissions 區塊，賦予寫入權限
    permissions:
      contents: write

    steps:
      # Step 1: 把你的 repo 程式碼載下來
      - uses: actions/checkout@v4

      # Step 2: 執行產生 SVG 的主要 Action
      - uses: cyprieng/github-breakout@main
        with:
          github_username: 'yijiunchin'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      # Step 3: 自動把新產生的 SVG 檔案 commit 回你的 repo
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: update github-breakout svgs'
          file_pattern: 'output/*.svg'
